using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics.CodeAnalysis;
using System.Diagnostics.Contracts;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;

namespace EulerProject.ProblemCollection.Problem051_100
{
    public class Problem061 : ProblemBase
    {
        public override string Description
        {
            get
            {
                return @"
Problem 61 - Cyclical Figurate Numbers

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:

Triangle	 	P3(n) = n(n+1)/2    1,3,6,10,15...
Square	 	    P4(n) = n^2         1,4,9,16,25...
Pentagonal	 	P5(n) = n(3n-1)/2   1,5,12,22,35...
Hexagonal	 	P6(n) = n(2n-1)     1,6,15,28,45...
Heptagonal	 	P7(n) = n(5n-3)/2   1,7,18,34,55...
Octagonal	 	P8(n) = n(3n-2)     1,8,21,40,65...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
2. Each polygonal type: triangle (P3(127) = 8128), square (P4(91) = 8281), and pentagonal (P5(44) = 2882)), is represented by a different number in the set.
3. This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
";
            }
        }

        public override int ProblemNumber
        {
            get
            {
                return 61;
            }
        }

        public override string Solution1()
        {
            List<int> numberList = new List<int>();

            int n = 1;
            int p = 0;
            while (p < 10000)
            {
                p = n * (3 * n - 2);
                if (p > 1000 && p < 10000) numberList.Add(80000 + p);
                p = n * (5 * n - 3) / 2;
                if (p > 1000 && p < 10000) numberList.Add(70000 + p);
                p = n * (2 * n - 1);
                if (p > 1000 && p < 10000) numberList.Add(60000 + p);
                p = n * (3 * n - 1) / 2;
                if (p > 1000 && p < 10000) numberList.Add(50000 + p);
                p = n * n;
                if (p > 1000 && p < 10000) numberList.Add(40000 + p);
                p = n * (n + 1) / 2;
                if (p > 1000 && p < 10000) numberList.Add(30000 + p);

                n++;
            }

            for (int i = 3; i <= 8; i++)
            {
                int count = numberList.Where(x => x / 10000 == i).Count();
                Console.WriteLine($"P{i} list count: {count}");
            }

            bool bFound = false;
            int sum = 0;
            foreach (int p1 in numberList.Where(x => x / 10000 == 8))
            {
                List<int> p2List = numberList.Where(x => (x / 100 % 100 == p1 % 100) && x / 10000 != p1 / 10000).ToList();
                if (p2List.Count== 0) continue;
                foreach (int p2 in p2List)
                {
                    List<int> p3List = numberList.Where(x => (x / 100 % 100 == p2 % 100) && x / 10000 != p1 / 10000 && x / 10000 != p2 / 10000).ToList();
                    if (p3List.Count== 0) continue;
                    foreach(int p3 in p3List)
                    {
                        List<int> p4List = numberList.Where(x => (x / 100 % 100 == p3 % 100) && x / 10000 != p1 / 10000 && x / 10000 != p2 / 10000 && x / 10000 != p3 / 10000).ToList();
                        if (p4List.Count== 0) continue;
                        foreach (int p4 in p4List)
                        {
                            List<int> p5List = numberList.Where(x => (x / 100 % 100 == p4 % 100) && x / 10000 != p1 / 10000 && x / 10000 != p2 / 10000 && x / 10000 != p3 / 10000 && x / 10000 != p4 / 10000).ToList();
                            if (p5List.Count== 0) continue;
                            foreach (int p5 in p5List)
                            {
                                List<int> p6List = numberList.Where(x => (x / 100 % 100 == p5 % 100) && x / 10000 != p1 / 10000 && x / 10000 != p2 / 10000 && x / 10000 != p3 / 10000 && x / 10000 != p4 / 10000 && x / 10000 != p5 / 10000).ToList();
                                if (p6List.Count== 0) continue;
                                foreach (int p6 in p6List)
                                {
                                    if (p6 % 100 == p1 / 100 % 100)
                                    { 
                                        sum = p1 % 10000 + p2 % 10000 + p3 % 10000 + p4 % 10000 + p5 % 10000 + p6 % 10000;
                                        Console.WriteLine($"({p1/10000}){p1% 10000} ({p2/10000}){p2%10000} ({p3/10000}){p3%10000} ({p4/10000}){p4%10000} ({p5/10000}){p5%10000} ({p6/10000}){p6%10000}");
                                        bFound = true; 
                                        break; 
                                    }
                                }
                                if (bFound) break;
                            }
                            if (bFound) break;
                        }
                        if (bFound) break;
                    }
                    if (bFound) break;
                }
                if (bFound) break;
            }

            return sum.ToString();
        }
    }
}
